/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author edgarmed
 */
public class Pcobrar extends javax.swing.JPanel {

    /**
     * Creates new form Pcobrar
     */
    public Pcobrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txPlaca = new javax.swing.JTextField();
        lPlaca = new javax.swing.JLabel();
        lSalida = new javax.swing.JLabel();
        txSalida = new javax.swing.JTextField();
        cbUbicacion = new javax.swing.JCheckBox();
        btRegresar = new javax.swing.JButton();

        lPlaca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lPlaca.setForeground(new java.awt.Color(255, 255, 255));
        lPlaca.setText("Ingrese la placa del vehículo:");

        lSalida.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lSalida.setForeground(new java.awt.Color(255, 255, 255));
        lSalida.setText("Ingrese kilometro de salida:");

        cbUbicacion.setText("Cobobrar en la Ubicación de esta caseta");

        btRegresar.setText("Canselar/Regresar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lPlaca)
                            .addComponent(lSalida))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(cbUbicacion)
                        .addGap(62, 62, 62)
                        .addComponent(btRegresar)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPlaca))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSalida)
                    .addComponent(txSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbUbicacion)
                    .addComponent(btRegresar))
                .addContainerGap(163, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btRegresar;
    public javax.swing.JCheckBox cbUbicacion;
    private javax.swing.JLabel lPlaca;
    private javax.swing.JLabel lSalida;
    public javax.swing.JTextField txPlaca;
    public javax.swing.JTextField txSalida;
    // End of variables declaration//GEN-END:variables
}
